root = "."
testdata_dir = "testdata"
tmp_dir = "dist"

[build]
  bin = "./run.sh run"
  cmd = "./run.sh build"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "frontend/node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = true
  full_bin = ""
  include_dir = []
  include_ext = ["go"]
  kill_delay = 500
  log = "air.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false